version: "3.5"

services:
    go:
        container_name: go-service
        image: my-go:v1.0
        ports:
            - 8080:8080
        environment: 
            - PORT=8080
            # - PREFIX=/goo
        network_mode: global_network
    nginx:
        container_name: nginx80
        image: nginx:latest
        ports:
            - 80:80
        network_mode: global_network
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            # - ./access.log/:/var/log/nginx/access.log

# networks: 
#     global_network:
#         name: global_network
